spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/board
      username: root
      password: dustn@@0317
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      repositories:
        enabled: false
expire:
  defaultTime: 3600
mybatis:
  mapper-locations: classpath:mappers/*.xml
